- .gitignore
- scratch/minecraft.js
- web/src/main/java/ch/vorburger/minecraft/storeys/web/ActionsConsumer.java
- web/src/main/java/ch/vorburger/minecraft/storeys/web/LoginCommand.java
- web/src/main/java/ch/vorburger/minecraft/storeys/web/NotLoggedInException.java
- web/src/main/java/ch/vorburger/minecraft/storeys/web/RSAUtil.java
- web/src/main/java/ch/vorburger/minecraft/storeys/web/StoreysWebPlugin.java
- web/src/test/java/ch/vorburger/minecraft/storeys/web/RSAUtilTest.java
@vorburger don't like the static HashMap, but initial version that works
> added login command to generate a personal link to the scratchx UI

- scratch/build.gradle
> make build incremental by specifying the input files for the tasks

- scratch/karma.conf.js
- scratch/package-lock.json
- scratch/package.json
also added package-lock.json as discussed in #18
> add html reporter

- build.gradle
stumbled upon this while trying to fix https://github.com/vorburger/minecraft-storeys-maker/issues/22
> removed anyway un-used spongepowered.plugin

- build.gradle
see https://github.com/tbroyer/gradle-errorprone-plugin/issues/66
> bump error-prone version, and fix incorrect classpath

- scratch/src/index.ts
- web/src/main/java/ch/vorburger/minecraft/storeys/web/LoginCommand.java
- web/src/test/java/ch/vorburger/minecraft/storeys/web/SeleniumTest.java
@vorburger no longer hardcoded to locahost:8080
> made event bus url a url parameter as well

- api/src/main/java/ch/vorburger/minecraft/storeys/api/Minecraft.java
- scratch/package-lock.json
- scratch/src/index.html
- scratch/src/index.ts
- scratch/src/test.ts
- web/src/main/java/ch/vorburger/minecraft/storeys/api/impl/MinecraftImpl.java
- web/src/test/java/ch/vorburger/minecraft/storeys/web/SeleniumTest.java
- web/src/test/java/ch/vorburger/minecraft/storeys/web/test/TestMinecraft.java
> added narrate command to api

- scratch3/build.gradle
- settings.gradle
@vorburger all that is needed now is a way to serve this either using nginx or the static verticle you can decide ;)
> gradle build that builds our fork of scratch3 with minecraft blocks

- scratch3/build.gradle
- web/build.gradle
web-1.0.0-SNAPSHOT-all.jar just jumped from 3.4 MB to 25 MB ... ;-)
see http://localhost:7070/scratch3/index.html
> serve new scratch3/ static web content via StaticWebServerVerticle

- api/package-lock.json
- api/package.json
- api/src/main/typescript/observable-wrapper.ts
- api/tsconfig.json
- api/webpack.config.js
fixes: https://github.com/vorburger/minecraft-storeys-maker/issues/59
> observable wrapper around proxy and change it to npm module

- api/package-lock.json
- api/package.json
- scratch/package-lock.json
- scratch/package.json
> updated to socks.js to 1.1.5 to remove CVE

- scratch/package-lock.json
- scratch/package.json
another stab at #100 in favor of #102
> cve-fix minimal updates version

- storeys/src/main/java/ch/vorburger/minecraft/storeys/events/EventService.java
fixes: https://github.com/vorburger/minecraft-storeys-maker/issues/87
> cancel event on right click

- scratch3-server/package-lock.json
- scratch3-server/package.json
- scratch3-server/scratch-server.js
- storeys/src/main/java/ch/vorburger/minecraft/storeys/events/EventService.java
- storeys/src/main/java/ch/vorburger/minecraft/storeys/events/LocatableInBoxCondition.java
- web/src/main/java/ch/vorburger/minecraft/storeys/api/impl/MinecraftImpl.java
- web/src/main/java/ch/vorburger/minecraft/storeys/web/ActionsConsumer.java
- web/src/main/java/ch/vorburger/minecraft/storeys/web/LocationToolListener.java
- web/src/main/java/ch/vorburger/minecraft/storeys/web/StoreysWebPlugin.java
- web/src/main/java/ch/vorburger/minecraft/storeys/web/location/LocationHitBox.java
- web/src/main/java/ch/vorburger/minecraft/storeys/web/location/LocationPairSerializer.java
In the config the locations that are made by the player are saved.
So when a scratch file is run on the server the locations will still work.
> fix: location tool locations are now saved

- .dockerignore
- Revert "rm .dockerignore (#262)"
- add Dockerfile itself to .dockerignore
> Revive .dockerignore

- README.md
> changed wording to make it more clear

- README.md
clarification for #270
based on https://github.com/itzg/docker-minecraft-server#opadministrator-players
> Add OPS to README.

- Dockerfile
- README.md
> Copy JAR to /mods/ instead of /data (fixes #275)

- api/build.gradle
> Fix broken classpath in IDE

- api/package-lock.json
- scratch/package-lock.json
Running the build locally adds this.
@edewit merge this?
> vertx3-eventbus-client added to package-lock.json (x2)

- scratch3-server/scratch-server.js
> keep track of running scratch scripts and stop execution when scrips are removed

- web/src/main/java/ch/vorburger/minecraft/storeys/web/NodeStarter.java
- web/src/main/java/ch/vorburger/minecraft/storeys/web/StoreysWebPlugin.java
> Fix NodeStarter error handling

- engine/README.md
- engine/build.gradle
- engine/prompt-client.html
- engine/src/main/java/study/learn/storeys/engine/Interactlet.java
- engine/src/main/java/study/learn/storeys/engine/Main.java
- engine/src/main/java/study/learn/storeys/engine/prompters/SimplePrompter.java
- engine/src/main/java/study/learn/storeys/engine/prompters/WebSocketPrompterIO.java
- engine/src/main/java/study/learn/storeys/engine/prompters/WebSocketServer.java
- engine/src/main/java/study/learn/storeys/engine/prompters/WebsocketPrompterIO.java
Didn't want to change the API to much, so worked around it
not being async a bit.
> Initial version of engine websocket implementation

- TODO.md
- storeys/src/main/java/ch/vorburger/minecraft/storeys/TextSplitter.java
- storeys/src/main/java/ch/vorburger/minecraft/storeys/model/TitleAction.java
- storeys/src/test/java/ch/vorburger/minecraft/storeys/util/MoreStringsTest.java
> Fix  ugly LF seen in title of test.story

- TODO.md
@edewit this is the thing I meant
Could be fun (later)
> Add https://github.com/tkellogg/dura to TODO

- README.md
- TODO.md
- docs/commands.md
- docs/develop.md
- docs/faq.md
- docs/ops.md
- docs/story.md
- docs/testing.md
- done.md
> Simplify README

- Dockerfile
- Dockerfile-local
- web/build.gradle
- web/src/main/java/ch/vorburger/minecraft/storeys/web/NodeStarter.java
@edewit how about this for #313?
I've tested that [our testing scenario](https://github.com/OASIS-learn-study/minecraft-storeys-maker/blob/develop/docs/testing.md#scratch-30) still works with this - all good.
> Replace Node/NPM frontend-plugin-core with exec (fixes #313)

- TODO.md
- docs/testing.md
- minecraft-server-test-data/config/storeys-web/stories/js.story
- minecraft-server-test-data/config/storeys-web/stories/test.story
@edewit how about this now already, just to have something to test with (even if it's still somewhat broken; see #301)
> Add initial js.story

- storeys/src/test/java/ch/vorburger/minecraft/storeys/model/parser/StoryParserTest.java
- storeys/src/test/resources/parse-test.story
The #332 for #301 actually fixed #281 as well;
this just adds non-regression test coverage for that.
> Add moar test coverage (fixes #281)

- minecraft-server-test-data/config/storeys-web/stories/js.story
- minecraft-server-test-data/config/storeys-web/stories/test.story
@edewit this seems clearer split like this, to me, and more in-line with [our current testing](https://github.com/OASIS-learn-study/minecraft-storeys-maker/blob/develop/docs/testing.md)
Merge if OK for you?
> Clearly separate test.story and js.story

- storeys/src/main/java/ch/vorburger/minecraft/storeys/model/parser/StoryParser.java
- storeys/src/test/java/ch/vorburger/minecraft/storeys/model/parser/StoryParserTest.java
> removed the NopAction from the story and fixed newline

- scratch3/build.gradle
> made build incremental based on package.json

- storeys/src/main/java/ch/vorburger/minecraft/storeys/events/EventService.java
> propagate events so that other actions are still called

- build.gradle
fixes #349
@edewit merge this?
> Fix Gradle allproject/subprojects confusion (fixes #349)

- blockly/src/App.tsx
- blockly/src/blockly/BlocklyComponent.tsx
- blockly/src/blockly/storeys/code.ts
- blockly/vite.config.ts
Now when blocks are create deleted or changed the upload
is trigged
> make blockly upload the code automatacally

- blockly/src/App.tsx
- blockly/src/blockly/storeys/code.ts
> when right clicked

- blockly/src/App.tsx
- blockly/src/blockly/storeys/storeys.d.ts
- blockly/src/monaco/CodeEditor.tsx
> added type information on the monaco editor

- Dockerfile-build
Updated node to LTS version
fixes: #407
> updated node to LTS version

- web/src/main/java/ch/vorburger/minecraft/storeys/web/StaticWebServerVerticle.java
follow-up to #414, see #411
@edewit review and merge when build passed?
> Fix load of workspace (#411)

- config/eclipse/formatter.xml
- web/src/main/java/ch/vorburger/minecraft/storeys/web/StaticWebServerVerticle.java
@edewit merge this, once the build passed?
> Minor: Fix annotation formatting and Eclipse Formatter config
